
(function(){
    "use strict";
    
    
    var paraElements = [];
    
    paraElements[0] = document.getElementById("paragraph1");
    paraElements[1] = document.getElementById("paragraph2");
    paraElements[2] = document.getElementById("paragraph3");
    
    var paragraphs = [];
    
    paragraphs[0] = "Web design encompasses many different skills and disciplines in the production and maintenance of websites. The different areas of web design include web graphic design; interface design; authoring, including standardised code and proprietary software; user experience design; and search engine optimization. Often many individuals will work in teams covering different aspects of the design process, although some designers will cover them all.[1] The term web design is normally used to describe the design process relating to the front-end (client side) design of a website including writing mark up. Web design partially overlaps web engineering in the broader scope of web development. Web designers are expected to have an awareness of usability and if their role involves creating mark up then they are also expected to be up to date with web accessibility guidelines.";
    paragraphs[1] = "Although web design has a fairly recent history, it can be linked to other areas such as graphic design. However web design can also be seen from a technological standpoint. It has become a large part of people’s everyday lives. It is hard to imagine the Internet without animated graphics, different styles of typography, background and music.";
    paragraphs[2] = "Web designers use a variety of different tools depending on what part of the production process they are involved in. These tools are updated over time by newer standards and software but the principles behind them remain the same. Web designers use both vector and raster graphics editors to create web-formatted imagery or design prototypes. Technologies used to create websites include W3C standards like HTML and CSS, which can be hand-coded or generated by WYSIWYG editing software. Other tools web designers might use include mark up validators[7] and other testing tools for usability and accessibility to ensure their web sites meet web accessibility guidelines.[8]";
    
    for (var i = 0; i < paraElements.length; i++) {
        if(paraElements[i]) {
         paraElements[i].textContent = paragraphs[i];
        }
    }
    
    
})();